---
image: golang:alpine

variables:
  GO111MODULE: "on"
  CGO_ENABLED: 0
  GOOS: "linux"

before_script:
  # gcc and musl-dev required for cgo
  - apk update && apk upgrade && apk add --no-cache git gcc musl-dev

stages:
  - build
  - test

compile:
  tags:
    - docker
  stage: build
  script:
    - go build -a -installsuffix cgo -o $CI_PROJECT_DIR/$CI_PROJECT_NAME

  artifacts:
    paths:
      - $CI_PROJECT_NAME

test:
  tags:
    - docker
  stage: test
  script:
    - echo "Beep Beep Boop Boop"
    - echo "Doop Doop"